### ISSUE TITLE
Can the widget deal with other projections like British National Grid?

### ISSUE THREAD

**Issue by cconnolly91** [Esri/workflowmanager-createjob-widget#5]
Hi there, 

I've set up the widget with our instance of WFM and it works really well when creating jobs from existing features. If I create a job by adding a new point/polygon on the map, the job is created but the AOI/POI moves and appears off the coast of Africa. 
![image](https://user-images.githubusercontent.com/13254969/40239475-1a5799c0-5aae-11e8-955a-9cf20af26245.png)

This is something that happens when there is a projection/transformation issue between BNG and WGS 1984 WM. 
As we're based in the UK, I created the Workflow Manager database using British National Grid for the AOI_Spatial_Reference in the Create Workflow Database tool. 

The webmap used in Web AppBuilder has this as the basemap: https://www.arcgis.com/home/item.html?id=0895f24cf85b4251990a24305447ded7 

Is there anything else I should do? Like republishing the aoi/poi layers with a transformation from WGS 1984 WM or changing something in the widget files?

Any information would be very helpful, thanks!

Carmel

**Comment by llam001** [comment]
Hello Carmel,

Thank you for bringing this issue to our attention.  After some investigation, it was discovered that for drawn AOIs, the widget code converts the geometry from Web Mercator coordinates (spatial reference used in ArcGIS Online standard basemaps) to geographic.  We will need to address converting from other spatial references when using different basemaps other than standard ArcGIS Online basemaps in a future release of the widget.

Looking at the [basemap](https://tiles.arcgis.com/tiles/qHLhLQrcvEnxjtPr/arcgis/rest/services/OS_Open_Background_2/MapServer) you're using, I see that it is using the [BNG WKID=27700](https://communityhub.esriuk.com/geoxchange/2012/3/26/coordinate-systems-and-projections-for-beginners.html) projected coordinate system.  If your Workflow Manager AOI/POI layers are in the same projection as your basemap, you can try removing the conversion code in the widget and see if that works for you.

Steps to update the widget code:
* Locate and edit the `workflowmanager-createjob-widget\widgets\WorkflowManagerCreateJobs\Widget.js` file
* On line 756-762, replace the following code:
```
	if (commontype === 'point') {
	  this.aoi = WebMercatorUtils.webMercatorToGeographic(graphic.geometry);
	  this.aoi.type = 'point';
	} else if (commontype === 'polygon') {
	  this.aoi = WebMercatorUtils.webMercatorToGeographic(graphic.geometry);
	  this.aoi.type = 'polygon';
	}
```
* with the following (removing conversion code)
```
	if (commontype === 'point') {
	  this.aoi = graphic.geometry;
	  this.aoi.type = 'point';
	} else if (commontype === 'polygon') {
	  this.aoi = graphic.geometry;
	  this.aoi.type = 'polygon';
	}
```

Let us know if this works for you. 

Thanks,
Lalaine

**Comment by cconnolly91** [comment]
Hi Lalaine, 

Thanks for your quick reply!
I copied the widget, changed the code and built a new Web AppBuilder widget but no luck, new features are still moved.

The main purpose of using the widget is the ability to create jobs from existing polygons, but the ability to create jobs from new points/polygons is still required. We'll keep an eye on the widget and look forward to updates!

Carmel

**Comment by llam001** [comment]
Hi Carmel,

After making the changes to the widget, you will also need to do the following for changes to take effect:
* Republish the widget to portal
* Create a new web application in Web AppBuilder that uses the republished widget

These steps will ensure that the code changes to the widget get propagated to portal and the web app. 

Thanks,
Lalaine

**Comment by cconnolly91** [comment]
Hi Lalaine, 

A restart of the system has kicked the code changes in and adding new features works great now, thanks for you help!

Carmel

**Comment by llam001** [comment]
Hi Carmel,

Great to hear that fixed your issue!

Thanks,
Lalaine
